import type { Metadata } from "next";
import { Inter, Cormorant_Infant, DM_Mono } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const cormorant_infant = Cormorant_Infant({ subsets: ["latin"], weight: "400", variable: "--font-cormorant-infant" })
const dm_mono = DM_Mono({subsets:["latin"], weight: "400", variable: "--font-dm-mono"})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${cormorant_infant.variable} ${dm_mono.variable}`}>{children}</body>
    </html>
  );
}
